services:
  valkey:
    image: valkey/valkey:latest
    restart: always
    networks:
      - search_network
    healthcheck:
      test: ['CMD', 'valkey-cli', 'ping']
      interval: 10s
      timeout: 60s
      retries: 5


  postgres:
    image: postgres:16-alpine
    restart: always
    networks:
      - search_network
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=search
    ports:
      - '127.0.0.1:5433:5432/tcp'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', '$$POSTGRES_DB']
      interval: 10s
      timeout: 60s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data

  search:
    image: search:latest-standalone
    networks:
      - search_network
    depends_on:
      postgres:
        condition: service_healthy
      valkey:
        condition: service_healthy
    ports:
      - 3000:3000/tcp
    environment:
      - SEARCH_POSTGRES_HOST=postgres
      - SEARCH_POSTGRES_USER=postgres
      - SEARCH_POSTGRES_PASSWORD=postgres
      - SEARCH_POSTGRES_DATABASE=search
      - SEARCH_REDIS_HOST=valkey

volumes:
  postgres:

networks:
  search_network: